### ISSUE TITLE
[Bug]: Compilation errors occur when using `extensionAlias` with package names ending in `*.js`

### ISSUE THREAD

**Issue by Fitz6** [web-infra-dev/rsbuild#3557] opened 2024-09-25 08:15 UTC
### Version

```sh
Browsers:
  Edge: Chromium (127.0.2651.74)
npmPackages:
  @rsbuild/core: 1.0.6 => 1.0.6
```

### Details

In version 1.0.6, I noticed that the `rspack.config.js` generated by rsbuild includes an `extensionAlias` configuration. 
If you install `packageA`, which has dependencies with package names ending in `*.js`, and `packageA` includes a `node_modules` folder, you'll encounter a compilation error.

```shell
 × All of the aliased extensions are not found for ....
```

You can reproduce it through the following steps: 

```shell
# Choose the vanilla-ts template
npm create rsbuild@latest

npm install mathjs && mkdir node_modules/mathjs/node_modules
# or
pnpm install mathjs
```

```javascript
// src/index.ts
import 'mathjs'
```

```shell
npm run build
```

### Reproduce link

https://rsbuild.dev/guide/start/quick-start

### Reproduce Steps

As mentioned above.

**Comment by chenjiahan** [comment] 2024-09-25 08:36
I still cannot reproduce this issue, but the edge case bugs seem to exist and I will revert the feature before we fix it.

**Comment by abenhamdine** [comment] 2024-09-25 09:52
I also get the same error message with module @ant-design/pro-layout

**Comment by Fitz6** [comment] 2024-09-25 12:15
> I still cannot reproduce this issue, but the edge case bugs seem to exist and I will revert the feature before we fix it.

Perhaps you missed some steps, such as not adding `import 'mathjs'` in `src/index.ts`, or there is no `node_modules` folder under the `node_modules/mathjs` directory.
I just tried it on both Linux and MacOS, and I can reproduce the same issue.

**Comment by Fitz6** [comment] 2024-09-25 12:23
> I also get the same error message with module @ant-design/pro-layout

This is the same issue because `@ant-design/pro-layout` depends on `omit.js`.

**Comment by SoonIter** [comment] 2024-09-26 01:08
let me reproduce it and fix in rspack-resolver

**Comment by chenjiahan** [comment] 2024-11-05 08:41
Fixed by https://github.com/web-infra-dev/rspack-resolver/pull/31

**Closed by chenjiahan** 2024-11-05 08:41 UTC
Labels: 🐞 bug, 🎯 upstream
