### ISSUE TITLE
[Bug]: ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization in dev mode

### ISSUE THREAD

**Issue by khangviet1996** [web-infra-dev/rsbuild#2862] opened 2024-07-10 03:16 UTC
### Version

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 7.82 GB / 31.87 GB
  Browsers:
    Chrome: 126.0.6478.127
    Edge: Chromium (126.0.2592.87)
    Internet Explorer: 11.0.19041.4355
  Packages: rsbuild 1.0.0-alpha.6 and 1.0.0-alpha.7
```

### Details

![image](https://github.com/web-infra-dev/rsbuild/assets/168616012/664ae91a-27d0-4c5d-87e6-42cf4275b58a)
![image](https://github.com/web-infra-dev/rsbuild/assets/168616012/4cacc735-f651-4d4c-9cb4-d4e8af2e9f66)

I'm facing an issue in development mode where everything works fine in version v7.0.10 and in build mode in the latest version. Essentially, index.js acts as a barrel file:
```
import User from './avatar/User';
import UserOptions from './menu/UserOptions';
import HeaderOpenItem from './headerOpenItem/HeaderOpenItem';
import MeetingNotification from './menu/MeetingNotification';

export const UserAvatar = User;
export const UserMenu = UserOptions;

export { HeaderOpenItem, MeetingNotification };
```
I don't know the reason for the issue yet, so I can't provide more details at the moment. I'll add more information once I identify the cause.

### Reproduce link

no produce

### Reproduce Steps

```pnpm run dev```

**Comment by SoonIter** [comment] 2024-07-10 03:57
related to https://github.com/web-infra-dev/rspack/pull/6861

Could you try to turn on this configuration?

```
// rsbuild.config.ts
tools: {
	rspack: {
		output: {
			environment: {
				const: false
			}
		}
	}
}
```

If this does not solve this issue, please provide a reproduction repository.

**Comment by khangviet1996** [comment] 2024-07-10 05:00
Thank you so much!

**Comment by ahabhgk** [comment] 2024-07-10 06:17
Could you provide a minimal reproduce so I can debug further to fix the root issue here

**Comment by khangviet1996** [comment] 2024-07-10 07:00
> Could you provide a minimal reproduce so I can debug further to fix the root issue here

This is my company's private project, so I'll debug and create a minimal reproduction. However, after adding the following configuration:
But added ```tools: {
	rspack: {
		output: {
			environment: {
				const: false
			}
		}
	}
}```, 
everything seems fine
Thank you so much!

**Comment by chenjiahan** [comment] 2024-07-12 05:26
I will close this issue due to lack of reproduction. If anyone encountered the same issue, providing a reproduction will be very helpful for debugging.

**Closed by chenjiahan** 2024-07-12 05:26 UTC
Labels: 🐞 bug

**Comment by SoonIter** [comment] 2024-07-29 06:54
This problem is due to circular references, and it is not a rspack/webpack issue.

## Summary 

`output.environment.const = false`

This configuration will hide some potential runtime errors in the case of circular references.

We should try our best to use `output.environment.const = true` and repair circular references at compile time, `output.environment.const = false` can be used in an emergency.

some details and reproduction

https://github.com/SoonIter/circular-reference-rspack
