### ISSUE TITLE
[Bug]: Creating a project - causes an error

### ISSUE THREAD

**Issue by StarkElessar** [web-infra-dev/rsbuild#2384] opened 2024-05-19 12:45 UTC
### Version

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz
    Memory: 23.06 GB / 31.92 GB
Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.19041.4355
```

### Details

Current version of bun.js 1.1.8. I can't create a project, the error is on the screenshot.
![image](https://github.com/web-infra-dev/rsbuild/assets/87839232/d864bf90-3bdd-4050-97c6-d7c2ef99cc9d)

### Reproduce link

https://github.com/web-infra-dev/rsbuild/assets/87839232/d864bf90-3bdd-4050-97c6-d7c2ef99cc9d

### Reproduce Steps

bun create rsbuild@latest

**Comment by SoonIter** [comment] 2024-05-20 16:54
Do you have the same problem when using `npm create rsbuild@latest`? 
I think this is an issue related to bun.

**Comment by chenjiahan** [comment] 2024-05-21 08:20
I cannot reproduce this issue on my device:

![image](https://github.com/web-infra-dev/rsbuild/assets/7237365/0f3cf89a-b36e-43bf-935c-7178e5aa1fd8)

**Comment by StarkElessar** [comment] 2024-05-21 10:31
Good afternoon, I closed GitBash and opened terminal via cmd on windows 10 and everything worked successfully! Is it ok to close the problem? Or is it still a problem that on windows10 you can't create a project in the GitBash terminal?

**Comment by chenjiahan** [comment] 2024-05-21 10:40
Haha, I think we can close this issue 😄 maybe related to bun Windows support.

**Closed by chenjiahan** 2024-05-21 10:40 UTC
Labels: 🐞 bug
