### ISSUE TITLE
[Bug]: UnoCSS HMR does not work

### ISSUE THREAD

**Issue by bosens-China** [web-infra-dev/rsbuild#3528] opened 2024-09-22 05:36 UTC
### Version

```sh
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 17.30 GB / 31.86 GB
  Browsers:
    Edge: Chromium (128.0.2739.54)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @rsbuild/core: ^1.0.1 => 1.0.5
    @rsbuild/plugin-less: ^1.0.1 => 1.0.1
    @rsbuild/plugin-react: ^1.0.1 => 1.0.2
```

### Details

1. 按照文档安装 https://rsbuild.dev/zh/guide/basic/unocss
2. 在项目中使用class类名
3. 浏览器没有正确显示

### Reproduce link

https://github.com/bosens-China/picture-bed/tree/master/packages/interface

### Reproduce Steps

1. 克隆这个项目
2. pnpm install
3. cd /packages/interface
4. pnpm run dev
5. 随便在文件任意位置添加class，例如p-32px
6. 观察浏览器style注入情况

**Comment by 9aoy** [comment] 2024-09-23 07:36
Turn on the hmr configuration in your project, everything looks fine.

https://github.com/bosens-China/picture-bed/blob/master/packages/interface/rsbuild.config.ts#L17

<img width="689" alt="image" src="https://github.com/user-attachments/assets/f8d250d1-5a31-41ff-9819-b4d430a45049">

**Comment by bosens-China** [comment] 2024-09-24 06:39
@9aoy 我录制了一个视频你可以看下，复线步骤
1. 开启hmr
2. 在一个新的元素，直接添加classname

https://cdn.z.wiki/autoupload/20240924/Mtsu/%E5%BD%95%E5%B1%8F2024-09-24_14.29.04.mov

**Comment by 9aoy** [comment] 2024-09-25 03:05
This problem is caused by the recent version of `@unocss/postcss` not adding the postcss dependency correctly. Needs to be fixed in `@unocss/postcss`.

![image](https://github.com/user-attachments/assets/1e1cd4f4-b6e6-4a37-990a-ec3f7efb6b3e)

https://github.com/unocss/unocss/commit/3ccd4c8f9e31ab7643da7390477e679130f4110d#diff-4693bd37b5c3bdb6333760a51bd95d59c108fe0893e24e1237babd281d8b01e4R138-R153

**Closed** 2024-09-26 09:36 UTC
Labels: 🐞 bug, 🎯 upstream
