### ISSUE TITLE
[Bug]: @rsbuild/plugin-eslint The plug-in is only detected at startup. Modifying the code does not update the detection status.

### ISSUE THREAD

**Issue by yangcore** [web-infra-dev/rsbuild#2151] opened 2024-04-19 09:37 UTC
### Version

```sh
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 1.23 GB / 15.77 GB
  Browsers:
    Edge: Chromium (123.0.2420.81)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @rsbuild/core: ^0.6.3 => 0.6.4
    @rsbuild/plugin-eslint: ^0.6.4 => 0.6.4
    @rsbuild/plugin-vue2: ^0.6.3 => 0.6.3
```

### Details

![image](https://github.com/web-infra-dev/rsbuild/assets/20217483/1ffb5846-de9e-4212-8758-f6f7d6dac002)

### Reproduce link

Not available yet

### Reproduce Steps

yarn dev

**Comment by chenjiahan** [comment] 2024-04-19 10:00
This is a known issue, see: https://github.com/web-infra-dev/rsbuild/discussions/2089

**Comment by yangcore** [comment] 2024-04-25 16:19
> This is a known issue, see: #2089

I used eslint-rspack-plugin and found that everything was normal. Later I saw that hooks were changed in the submission record of eslint-rspack-plugin, as shown below
![image](https://github.com/web-infra-dev/rsbuild/assets/20217483/f38de763-2f43-4357-843c-618b05c9b9ad)
Then I changed the hooks of [eslint-webpack-plugin](https://github.com/webpack-contrib/eslint-webpack-plugin) that @rsbuild/plugin-eslint depends on, and found that @rsbuild/plugin-eslint runs Normal, but the speed is relatively slow. When it is not turned on during development, the compilation time is 0.9s, and after it is turned on, it takes 2.3s.

**Comment by chenjiahan** [comment] 2024-04-26 02:18
Yeah, ESLint will slow down the build process

**Comment by chenjiahan** [comment] 2024-04-26 02:20
@hardfist should we use `eslint-rspack-plugin` at the moment?

**Comment by hardfist** [comment] 2024-04-29 13:29
I think it's fine to use eslint-rspack-plugin

**Comment by chenjiahan** [comment] 2024-08-09 13:08
Duplicate of https://github.com/web-infra-dev/rspack/issues/6432.

**Closed by chenjiahan** 2024-08-09 13:08 UTC
Labels: 🐞 bug
