### ISSUE TITLE
[Bug]: After installing Acro, introduce custom CSS, the program exits directly

### ISSUE THREAD

**Issue by MinGuoGuo** [web-infra-dev/rsbuild#3514] opened 2024-09-19 14:17 UTC
### Version

```sh
mac 和window都会出现
```

### Details

rsbuild安装acro后引入自定义css，程序直接退出，webpack和vite都没问题，详情见仓库链接

### Reproduce link

https://gitee.com/xiangminya/rsbuild-demo

### Reproduce Steps

直接运行项目就会报错，注释掉入口文件的import '@arco-themes/vue-gi-demo/css/arco.css' 就会正常运行

**Comment by 9aoy** [comment] 2024-09-20 04:06
When I turn off `lightningcssLoader`, everything works fine. You can temporarily turn off `lightningcssLoader` through `tools.lightningcssLoader: false`. We will continue to investigate the cause.

https://rsbuild.dev/config/tools/lightningcss-loader#disable-loader

**Comment by MinGuoGuo** [comment] 2024-09-20 05:01
> When I turn off `lightningcssLoader`, everything works fine. You can temporarily turn off `lightningcssLoader` through `tools.lightningcssLoader: false`. We will continue to investigate the cause.
> 
> https://rsbuild.dev/guide/basic/css-usage#disabling-lightning-css

ok

**Comment by MinGuoGuo** [comment] 2024-09-20 05:01
> When I turn off `lightningcssLoader`, everything works fine. You can temporarily turn off `lightningcssLoader` through `tools.lightningcssLoader: false`. We will continue to investigate the cause.
> 
> https://rsbuild.dev/guide/basic/css-usage#disabling-lightning-css

ok. thinks

**Comment by MinGuoGuo** [comment] 2024-09-20 06:24
大佬，还有问题vue单文件里面，一旦添加或者删除style标签，编译也会直接，这个库就能复现

**Comment by 9aoy** [comment] 2024-09-20 06:44
> 还有问题vue单文件里面，一旦添加或者删除style标签，编译也会直接，这个库就能复现

see https://github.com/web-infra-dev/rspack/issues/7805

**Comment by MinGuoGuo** [comment] 2024-09-20 06:48
> > 还有问题vue单文件里面，一旦添加或者删除style标签，编译也会直接，这个库就能复现
> 
> see [web-infra-dev/rspack#7805](https://github.com/web-infra-dev/rspack/issues/7805)

ok. very very thinks

**Comment by GiveMe-A-Name** [comment] 2024-10-08 11:16
Reference to: https://github.com/parcel-bundler/lightningcss/issues/827

**Comment by chenjiahan** [comment] 2024-10-16 03:07
This issue should be fixed by https://github.com/parcel-bundler/lightningcss/pull/832, we will bump LightningCSS version when they release a new version.

**Closed by chenjiahan** 2024-10-16 03:07 UTC
Labels: 🐞 bug, 🎯 upstream
